"""empty message

Revision ID: 07082b1ae9f5
Revises: 4f516c84e0a6
Create Date: 2023-09-19 17:03:49.933270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07082b1ae9f5'
down_revision = '4f516c84e0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('training_status')

    # ### end Alembic commands ###
