"""empty message

Revision ID: 3f227689c7de
Revises: 64e305bc8d73
Create Date: 2023-09-19 16:15:42.629718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f227689c7de'
down_revision = '64e305bc8d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('role')
        batch_op.drop_column('content')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_phone', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['assigned_phone'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('assigned_phone')

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answer')
        batch_op.drop_column('question')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
