"""empty message

Revision ID: 4f516c84e0a6
Revises: 181c90e45c79
Create Date: 2023-09-19 16:48:53.002987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f516c84e0a6'
down_revision = '181c90e45c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['identity'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('identity')

    # ### end Alembic commands ###
