"""empty message

Revision ID: 672af8e8096f
Revises: 4f8254cfab29
Create Date: 2023-10-14 19:58:11.291757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672af8e8096f'
down_revision = '4f8254cfab29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('training_id')

    # ### end Alembic commands ###
