"""empty message

Revision ID: 8ce942bef2e5
Revises: 07082b1ae9f5
Create Date: 2023-09-30 16:07:24.867845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ce942bef2e5'
down_revision = '07082b1ae9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('langchain_pg_collection')
    # op.drop_table('langchain_pg_embedding')
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_id')

    # op.create_table('langchain_pg_embedding',
    # sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('uuid', name='langchain_pg_embedding_pkey')
    # )
    # op.create_table('langchain_pg_collection',
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey')
    # )
    # ### end Alembic commands ###
