"""empty message

Revision ID: a9ec24437830
Revises: 5bdcffacc751
Create Date: 2023-10-16 17:07:30.203087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ec24437830'
down_revision = '5bdcffacc751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('played', sa.Integer(), nullable=True))
        batch_op.drop_column('is_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('played')

    # ### end Alembic commands ###
